const { jsPDF } = require("jspdf");
const fs = require("fs");
const path = require("path");

const doc = new jsPDF({
  orientation: "portrait",
  unit: "mm",
  format: "a4"
});

// Title & Header Styling
doc.setFont("helvetica", "bold");
doc.setFontSize(22);
doc.setTextColor(16, 185, 129); // Emerald 600
doc.text("KisanLogic AI - PunjabiMandi.AI", 14, 20);

doc.setFontSize(10);
doc.setTextColor(100, 116, 139); // Slate 500
doc.setFont("helvetica", "normal");
doc.text("Executive Architecture, Research Innovations & Core Uniqueness Dossier", 14, 26);
doc.line(14, 30, 196, 30);

// Section 1: Key Features
doc.setFontSize(14);
doc.setTextColor(15, 23, 42); // Slate 900
doc.setFont("helvetica", "bold");
doc.text("1. KEY FEATURES & SYSTEM MODULES", 14, 40);

const features = [
  ["Grassroots Trilingual Localization Engine", "Instant context-based toggle across English, Hindi, and Punjabi (Gurmukhi)."],
  ["Ground-Reality APMC Profit Simulator", "Live moisture (Nami %) penalty deduction matrix and Arhti debt-trap contingency models."],
  ["Game-Theoretic Fair Freight Sharing", "Shapley Value cooperative game theory algorithm for fair shared transport cost distribution."],
  ["Inter-Mandi Spatial Arbitrage Optimizer", "Distance-matrix net revenue calculations after factoring round-trip diesel, toll, and freight."],
  ["AI Grain Quality & FCI Grading Shield", "Physical attribute compliance evaluator generating tamper-proof dispute defense certificates."],
  ["Biological Respiration & Decay Curve", "ASABE-standard non-linear daily viability loss curve and critical spoilage cliff projections."],
  ["Circular Stubble-to-Biofuel Valuation Engine", "Dynamic biomass yield calculators converting crop residue into guaranteed off-taker revenue."],
  ["Real-Time NASA FIRMS Satellite Tracker", "Live MODIS/VIIRS telemetry stream for district-level agricultural fire & stubble monitoring."],
  ["WDRA Smart Cold Storage & e-NWR Hubs", "Regional occupancy analytics with direct 7% government pledge loan eligibility markers."],
  ["Multilingual Voice IVR & Zero-Friction Dispatch", "Browser telephony voice synthesizer coupled with one-click WhatsApp and PDF reporting."]
];

doc.setFontSize(9);
let yPos = 48;
features.forEach(([title, desc], idx) => {
  doc.setFont("helvetica", "bold");
  doc.setTextColor(30, 41, 59);
  doc.text(`${idx + 1}. ${title}`, 14, yPos);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(71, 85, 105);
  doc.text(`   - ${desc}`, 14, yPos + 4.5);
  yPos += 11;
});

// Section 2: Core Uniqueness
doc.line(14, yPos + 2, 196, yPos + 2);
yPos += 10;

doc.setFontSize(14);
doc.setTextColor(15, 23, 42);
doc.setFont("helvetica", "bold");
doc.text("2. CORE UNIQUENESS & COMPETITIVE MOATS", 14, yPos);
yPos += 8;

const moats = [
  ["Beyond Price Discovery", "Bridges the gap between paper mandi rates and actual in-hand realization by subtracting ground deductions (moisture, debt, logistics)."],
  ["Positive Climate Economics", "Replaces stubble-burning penalties with profitable biomass supply chain monetization."],
  ["Farmer Bargaining Power", "Combines cooperative freight game theory with formal FCI grading defense against middle-man exploitation."],
  ["True Multimodal Accessibility", "Operable across local vernacular interfaces, automated voice synthesis, and low-bandwidth WhatsApp formats."]
];

moats.forEach(([title, desc], idx) => {
  doc.setFont("helvetica", "bold");
  doc.setTextColor(16, 185, 129);
  doc.text(`• ${title}:`, 14, yPos);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(51, 65, 85);
  const splitDesc = doc.splitTextToSize(desc, 175);
  doc.text(splitDesc, 18, yPos + 4.5);
  yPos += 12;
});

// Footer
doc.setFontSize(8);
doc.setTextColor(148, 163, 184);
doc.text("Generated by KisanLogic AI SOTA Engine • Hackathon & Pitch Deck Presentation Ready", 14, 285);

const outputPath = path.join(process.cwd(), "KisanLogic_Project_Features_Uniqueness.pdf");
fs.writeFileSync(outputPath, Buffer.from(doc.output("arraybuffer")));
console.log("PDF Successfully Saved to: " + outputPath);